### ISSUE TITLE
'Grid Distance' throws module error

### ISSUE THREAD

**Issue by jake1108** [apex-project/pyApex#10]
Trying to run the Grid distance tool throws the following error:

IronPython Traceback:
Traceback (most recent call last):
File "C:\Users\jake\AppData\Roaming\pyRevit\Extensions\pyApex.extension\pyApex.tab\QualityControl.panel\GridDistance.pushbutton\GridDistance_script.py", line 16, in <module>
ImportError: No module named typing

Script Executor Traceback:
IronPython.Runtime.Exceptions.ImportException: No module named typing
at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

( Revit environment: 2021.1.2 )

**Comment by melnikovalex** [comment]
Hi @jake1108 

Thank you for your issue and sorry for the inconvenience. That was a dumb mistake 🤦‍♂️ 

Please update the extension, now it should work.

**Comment by jake1108** [comment]
No probs, glad to help!
