### ISSUE TITLE
Copy Parameter error

### ISSUE THREAD

**Issue by cdfris** [apex-project/pyApex#13]
I get the following error after clicking Copy parameter function. Using Revit 2023 and pyRevit version 4.8.11.22151+0307-wip:277:2023.0.2

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Chris\AppData\Roaming\pyRevit\Extensions\pyApex.extension\pyApex.tab\Misc.panel\utils2.stack\CopyParameter.pushbutton\script.py", line 30, in <module>
 File "C:\Users\Chris\AppData\Roaming\pyRevit\Extensions\pyApex.extension\pyApex.tab\lib\pyapex_parameters.py", line 10, in <module>
AttributeError: 'Autodesk.Revit.DB' object has no attribute 'UnitType'

Script Executor Traceback:
System.MissingMemberException: 'Autodesk.Revit.DB' object has no attribute 'UnitType'
 at IronPython.Runtime.Binding.PythonGetMemberBinder.NamespaceTrackerDelegate.Target(CallSite site, Object self, CodeContext context)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at IronPython.Compiler.Ast.DynamicGetMemberExpression.GetMemberInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
 at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
 at IronPython.Runtime.PythonContext.InitializeModule(String fileName, ModuleContext moduleContext, ScriptCode scriptCode, ModuleOptions options)
 at IronPython.Runtime.Importer.LoadModuleFromSource(CodeContext context, String name, String path)
 at IronPython.Runtime.Importer.LoadFromDisk(CodeContext context, String name, String fullName, String str)
 at IronPython.Runtime.Importer.ImportFromPathHook(CodeContext context, String name, String fullName, List path, Func`5 defaultLoader)
 at IronPython.Runtime.Importer.ImportFromPath(CodeContext context, String name, String fullName, List path)
 at IronPython.Runtime.Importer.ImportTopAbsolute(CodeContext context, String name)
 at IronPython.Runtime.Importer.ImportModule(CodeContext context, Object globals, String modName, Boolean bottom, Int32 level)
 at IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
 at IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
 at IronPython.Runtime.Operations.PythonOps.ImportBottom(CodeContext context, String fullName, Int32 level)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by melnikovalex** [comment]
Hey there @cdfris!

Thank you so much for helping figuring out a problem in the first place.

I'm really sorry that I didn't get back to you sooner. Hopefully, you were able to figure out a solution to the task you were working on. Just wanted to let you know that I won't be able to provide support for the pyapex script anymore, though as now I will try to solve most critical issues but pull requests are prioritised

Anyway, I have now adjusted the script according to the API changes in Revit 2022 and 2023. I have also tried to make it work in earlier versions, though the code looks a bit messy.

#15 

Have a nice day
Alex
